import { PrismaClient } from "@prisma/client";
import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import ImageUpload from "../components/homes/ImageUpload";

const Home: NextPage = () => {
  return (
    <div className="prose lg:prose-lg">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default Home;
export const getServerSideProps: GetServerSideProps = async () => {
  const prisma = new PrismaClient();
  const homes = await prisma.home.findMany();
  return {
    props: { homes: JSON.parse(JSON.stringify(homes)) },
  };
};
